wandb:
  project: acai
  # Get your W&B token at https://wandb.ai/authorize
  token:
kowalski:
  host: kowalski.caltech.edu
  port: 443
  protocol: https
  token:
  collections:
    alerts: ZTF_alerts
fritz:
  token:
  protocol: https
  host: fritz.science

features:
  "20201130":
    - drb:
        norm: 1
    - diffmaglim:
        norm: 1
    - ra:
        norm: 1
    - dec:
        norm: 1
    - magpsf:
        norm: 1
    - sigmapsf:
        norm: 1
    - chipsf:
        norm: 1
    - fwhm:
        norm: 1
    - sky:
        norm: 1
    - chinr:
        norm: 1
    - sharpnr:
        norm: 1
    - sgscore1:
        norm: 1
    - distpsnr1:
        norm: 1
    - sgscore2:
        norm: 1
    - distpsnr2:
        norm: 1
    - sgscore3:
        norm: 1
    - distpsnr3:
        norm: 1
    - ndethist:
        norm: 1
    - ncovhist:
        norm: 1
    - scorr:
        norm: 1
    - nmtchps:
        norm: 1
    - clrcoeff:
        norm: 1
    - clrcounc:
        norm: 1
    - neargaia:
        norm: 1
    - neargaiabright:
        norm: 1

training:
  classes:
    acai_h:
      # value of label should refer to dataset.dN.csv
      label: h
      conv_branch: true
      # value should refer to features section of this config
      features: 20201130
      # balance ratio for the prevalent class. leave null to use all available data
      balance:
      weight_per_class: true
    acai_b:
    acai_o:
    acai_n:
    acai_v:
